### ISSUE TITLE
Specify Python version

### ISSUE THREAD

**Issue by lehmannro** [OpenTechSchool/python-beginners#19]
I know we have discussed this already but I cannot remember what we agreed upon:  Do we use Python 2 or Python 3?  We should advertise that somewhere.

In case we settle on Python 2, all ``print``s should use the statement form.

**Comment by Ivoz** [comment]
I hope it's pretty clear we want to teach newcomers Python 3 now. It's made a lot of progress and continued with 3.5 :D Cheers
