### ISSUE TITLE
Setting RGB colors is weird

### ISSUE THREAD

**Issue by metaodi** [OpenTechSchool/python-beginners#35]
When playing around with turtle a participant wanted to use RGB colors as described on the turtle page. He was used to enter RGB as 3 values from 0-255. It is not very clear how to do this, he always got this:

    TurtleGraphicsError: bad color sequence: (255, 40, 5)

An example might help.
To get it to work, you have to change the color mode of the turtle, then it works:

    turtle.colormode(255)
    turtle.color(255, 40, 5)

See also the [turtle documentation about colormode()](http://docs.python.org/2/library/turtle.html#turtle.colormode).

**Comment by AnteDieEnte** [comment]
Thank you so much!
