### ISSUE TITLE
Problem with simple_drawing

### ISSUE THREAD

**Issue by froottools** [OpenTechSchool/python-beginners#57]
import turtle

turtle.left(20)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)

turtle.left(100)

turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)

turtle.left(110)

turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.left(90)

**Comment by lehmannro** [comment]
Could you elaborate on the exact problem you encountered?  The code and its result look good.

**Comment by Ivoz** [comment]
If you still think there's an issue, please leave a comment and reopen. Cheers!
