### ISSUE TITLE
Site offline 404

### ISSUE THREAD

**Issue by hoh** [OpenTechSchool/python-beginners#70]
The Python for beginners website on http://opentechschool.github.io/python-beginners/en/index.html is unreachable, I get a 404 error from Github.

![image](https://cloud.githubusercontent.com/assets/404665/20520553/957a8548-b0a7-11e6-92fa-40a6c600a04f.png)

**Comment by lehmannro** [comment]
Weird — going to http://opentechschool.github.io/python-beginners/en/ (without the trailing `index.html`) works.

**Comment by lehmannro** [comment]
This seems to have resolved itself, I'm guessing it was a temporary glitch in Github Pages.

**Comment by lehmannro** [comment]
...and it resurfaces.  wat.

**Comment by phumberdroz** [comment]
works for me.

**Comment by lehmannro** [comment]
"18:06 CET  GitHub Pages sites continue to serve an increased number of 404 responses as we work to resolve the underlying cause."

Not fixing here.
